# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: বাংলায় লিখি... 
subtitle: "আমি বাংলায় মাতি উল্লাসে, করি বাংলায় হাহাকার, আমি সব দেখে শুনে ক্ষেপে গিয়ে করি বাংলায় চিৎকার"
email: sharmaojha2011@gmail.com
description: "তেমন কিছু বলার নেই এখানে। যা বলার পোস্ট ও কর্মের মাধ্যমেই বলছি। শুধু কিছু অর্থবোধক পদচিহ্ন এঁকে যেতে চাই এ পৃথিবীতে। পছন্দ শুধুই ঘুরে বেড়ানো, লেখালেখি এবং ভালবাসাবাসি। বাকি সব ঢং। বেঁচে থাকার জন্য কত ঢংই না করতে হয় মানুষকে! কর্মকাণ্ড ও লেখা বিষয়ে কোন প্রশ্ন বা জানার থাকলে মন্তব্য করুন।"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://lunaojha.github.io/bn/" # the base hostname & protocol for your site
gems: [jekyll-paginate]
paginate: 5
paginate_path: "/page:num/"
logo: "/images/weblogo.jpg"
github_username: lunaojha
disqus: lunaojha

# Build settings
markdown:           kramdown
highlighter:        rouge
kramdown:
  hard_wrap: true
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false

author:
  name: শর্মা লুনা (Sharma Luna)
  image: /images/me.jpg
  bio: 
  website: https://lunaojha.github.io/bn/

exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
sass:
 style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  ignore:
    envs: []
  blanklines: false
  profile: false
  startings: [html, head, body]

#social
fb_app_id:
fb_username:
first_name: 
last_name: 
gender: 
